name: country_icons
description: A flutter package with many country flag icons that you can use via the Image.asset method
version: 2.0.1
homepage: https://github.com/bytepark/country_icons

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=0.1.4"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_svg: ^0.22.0
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  assets:
    - icons/flags/png/
    - icons/flags/png/2.5x/
    - icons/flags/svg/
